USE tericttest;

CREATE TABLE IF NOT EXISTS Usuaris (
NICK				VARCHAR(75) NOT NULL UNIQUE,
Nom_Usuari			VARCHAR(75) NOT NULL,
Cognom1				VARCHAR(75),
Cognom2				VARCHAR(75),
PW					VARCHAR(39),
Avatar				LONGBLOB,
PRIMARY KEY (NICK));

CREATE TABLE IF NOT EXISTS Dataset (
ID_Foto				int AUTO_INCREMENT,
NICK				VARCHAR(75),
Num					INT,
Foto			    LONGBLOB,
PRIMARY KEY (ID_Foto),
FOREIGN KEY (NICK) REFERENCES Usuaris (NICK) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Administrador (
NICK				VARCHAR(75),
Mes_Info			VARCHAR(70),
PRIMARY KEY (NICK),
FOREIGN KEY (NICK) REFERENCES Usuaris (NICK) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Players (
NICK				VARCHAR(75) NOT NULL UNIQUE,
Info				VARCHAR(100),
PRIMARY KEY (NICK),
FOREIGN KEY (NICK) REFERENCES Usuaris (NICK) ON UPDATE CASCADE ON DELETE CASCADE);

CREATE TABLE IF NOT EXISTS Nivells (
ID_NIVELL			TINYINT,
Nom_nivell			VARCHAR(20),
PRIMARY KEY (ID_NIVELL));

CREATE TABLE IF NOT EXISTS Partides(
ID_PARTIDA			INT AUTO_INCREMENT,
NICK				VARCHAR(75),
ID_NIVELL 			TINYINT,
PUNTUACIO			INT,
PRIMARY KEY (ID_PARTIDA),
FOREIGN KEY (NICK) REFERENCES Players (NICK) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (ID_NIVELL) REFERENCES Nivells (ID_NIVELL) 
);

CREATE TABLE IF NOT EXISTS Moviments(
ID_JUGADA			INT AUTO_INCREMENT,
Num					INT,
Turn 				TINYINT,
PuntsIA 			TINYINT,
PuntsPlayer 		TINYINT,
CasellesIA 			TINYINT,
CasellesPlayer 		TINYINT,
GuanyaIA 			BOOL,
GuanyaPLAYER 		BOOL,
Taules 				BOOL,
OfegamentIA 		BOOL,
OfegamentPLAYER 	BOOL,
ID_PARTIDA			INT,
Estat				TEXT,
PRIMARY KEY (ID_JUGADA),
FOREIGN KEY (ID_PARTIDA) REFERENCES Partides (ID_PARTIDA) ON DELETE CASCADE
);

-- DEFINIREM UN ADMINISTRADOR. CARREGAREM LES SEVES FOTOS DESPRÉS APLICAREM EL SEGÜENT QUERY DES DE MYSQL WORKBENCH
-- insert into Administrador(NICK, Mes_Info)  values("Admin", "Eric Torrontera Ruiz");

-- INSERIM UN USUARI "Desconegut" PER PODER JUGAR DE MANRERA INCOGNITA SENSE IDENTIFICACIÓ
insert into Usuaris(NICK, Nom_Usuari)  values("Desconegut", "Incognito User");
insert into Players(NICK, Info)  values("Desconegut", "Incognito User");

insert into Nivells(ID_NIVELL, Nom_Nivell)  values(1, "Fàcil");
insert into Nivells(ID_NIVELL, Nom_Nivell)  values(2, "Normal");
insert into Nivells(ID_NIVELL, Nom_Nivell)  values(3, "Difícil");
insert into Nivells(ID_NIVELL, Nom_Nivell)  values(4, "Custom");